import { useState } from 'react';
import { Download, Trash2 } from 'lucide-react';

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 2 }).format(value || 0);
const compactMoney = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function ItemListPanel({ items, onChange, onRemove, onReset }) {
  const grandTotal = items.reduce((total, item) => total + item.quantity * item.unitPrice, 0);
  const [partyName, setPartyName] = useState(() => sessionStorage.getItem('catalogue-party-name') || '');
  const update = (id, key, value) => onChange(id, key, key === 'name' ? value : Math.max(0, Number(value) || 0));
  const changePartyName = (value) => { setPartyName(value); sessionStorage.setItem('catalogue-party-name', value); };
  const exportList = () => { const now = new Date(); const escape = (value) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;'); const rows = items.map((item, index) => `<tr><td>${index + 1}</td><td>${escape(item.name)}</td><td>${item.quantity}</td><td>${compactMoney(item.unitPrice)}</td><td>${compactMoney(item.quantity * item.unitPrice)}</td></tr>`).join(''); const documentHtml = `<!doctype html><html><head><meta charset="utf-8"><title>Item List</title><style>body{font-family:Arial,sans-serif;color:#172238;margin:40px}header{border-bottom:2px solid #f4a100;padding-bottom:16px;margin-bottom:22px}.header-row{display:flex;justify-content:space-between;align-items:flex-start}.party{font-size:19px;font-weight:700}.date-time{text-align:right}h1{text-align:center;font-size:22px;margin:18px 0 0}p{margin:0 0 6px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border:1px solid #cbd5e1;padding:9px;text-align:left}th{background:#f8fafc}td:nth-child(3),td:nth-child(4),td:nth-child(5){text-align:right}.total td{font-weight:bold;background:#fffbeb}@media print{body{margin:20px}}</style></head><body><header><div class="header-row"><div class="party">Party name: ${escape(partyName || '—')}</div><div class="date-time"><p><strong>Date:</strong> ${now.toLocaleDateString('en-IN')}</p><p><strong>Time:</strong> ${now.toLocaleTimeString('en-IN')}</p></div></div><h1>ITEM LIST</h1></header><table><thead><tr><th>S.No</th><th>Item Name</th><th>Quantity</th><th>Unit Price</th><th>Total Price</th></tr></thead><tbody>${rows}<tr class="total"><td colspan="4">Grand Total</td><td>${compactMoney(grandTotal)}</td></tr></tbody></table></body></html>`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([documentHtml], { type: 'text/html' })); link.download = `item-list-${now.toISOString().slice(0, 10)}.html`; link.click(); URL.revokeObjectURL(link.href); };
  return <aside className="order-3 flex min-h-0 shrink-0 flex-col border-t border-slate-200 bg-white lg:order-1 lg:w-[24rem] lg:border-r lg:border-t-0"><div className="border-b p-3"><div className="flex items-center justify-between"><div><h3 className="font-bold">Item list</h3><p className="text-xs text-slate-500">{items.length} line item{items.length === 1 ? '' : 's'}</p></div><div className="flex gap-1"><button type="button" onClick={onReset} disabled={!items.length} className="btn-secondary !px-2 !py-1.5 text-xs" aria-label="Reset list">Reset</button><button type="button" onClick={exportList} disabled={!items.length} className="btn-secondary !p-2" aria-label="Download item list"><Download size={16}/></button></div></div><label className="label mt-3">Party name</label><input className="field !py-2" value={partyName} onChange={e => changePartyName(e.target.value)} placeholder="Enter party name"/></div><div className="min-h-0 flex-1 overflow-auto"><table className="w-full min-w-[384px] table-fixed text-left text-xs"><colgroup><col className="w-6"/><col/><col className="w-11"/><col className="w-[4.25rem]"/><col className="w-[4.5rem]"/><col className="w-7"/></colgroup><thead className="sticky top-0 bg-slate-50 text-slate-500"><tr><th className="p-1.5">#</th><th className="p-1.5">Item</th><th className="p-1.5">Qty</th><th className="p-1.5">Unit</th><th className="p-1.5">Total</th><th/></tr></thead><tbody>{items.map((item, index) => <tr key={item.id} className="border-t border-slate-100 align-top"><td className="p-1.5 text-slate-500">{index + 1}</td><td className="p-1"><textarea rows="2" className="w-full resize-none rounded border border-slate-200 p-1.5 leading-snug" value={item.name} onChange={e => update(item.id, 'name', e.target.value)}/></td><td className="p-1"><input className="w-full rounded border border-slate-200 p-1.5" type="number" min="0" value={item.quantity} onChange={e => update(item.id, 'quantity', e.target.value)}/></td><td className="p-1"><input className="w-full rounded border border-slate-200 p-1.5" type="number" min="0" step="0.01" value={item.unitPrice} onChange={e => update(item.id, 'unitPrice', e.target.value)}/></td><td className="p-1.5 break-words font-medium">{compactMoney(item.quantity * item.unitPrice)}</td><td className="p-0.5"><button type="button" className="rounded p-1.5 text-red-600 hover:bg-red-50" onClick={() => onRemove(item.id)} aria-label={`Delete ${item.name}`}><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!items.length && <p className="p-6 text-center text-sm text-slate-500">Add products from the calculator to build a list.</p>}</div><div className="border-t bg-amber-50 p-3"><div className="flex items-center justify-between font-extrabold text-navy"><span>Grand total</span><span>{money(grandTotal)}</span></div></div></aside>;
}
